name: Integration-Regression-Playwright-Tests

on:
  workflow_dispatch:
    inputs:
      grep:
        type: string
        description: Filter test by grep E.g. - @end2endtest or @smoketest or @nightlytest or @regressiontest
        default: '@regression'
        required: true
      browsers:
        type: choice
        description: Type of browser to run the tests on. The first value will be the default
        required: true
        options:
          - '' #this will execute on all browsers
          - '-- --project=chromium'
          - '-- --project=firefox'
          - '-- --project=webkit' #safari
      workers:
        type: string
        description: number of parallel workers
        default: '1'
        required: false

# Run tests
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/test-runner.yml
    secrets: inherit
    with:
      environment: 'integration'
      grep: ${{ inputs.grep }}
      browsers: ${{ inputs.browsers }}
      workers: ${{ inputs.workers }}
